name: ${BuildId}

# CI triggers 
trigger: 
  batch: true 
  branches: 
    include: 
      - main 

pool: 
  vmImage: 'ubuntu-latest'

stages:
  - stage: Azure dev pipeline 
    display: Azure dev pipeline
    bash: | 
      echo "Running"