name: ${BuildId}

# CI triggers 
trigger: 
  batch: true 
  branches: 
    include: 
      - main 

pool: 
  vmImage: 'ubuntu-latest'

stages:
  - stage: DummyAzureStage
    displayName: 'Azure dev pipeline'